title: Transcription factor binding motif enrichment of Generation 3 Modules
description: Application of RcisTarget (an R package to analyze Transcription factor binding motif enrichment) on Generation 3 Modules
theme: jekyll-theme-cayman
github:
  is_project_page: false
